### ISSUE TITLE
BaseBot.play() allows corruption of public space

### ISSUE THREAD

**Issue by nchaudhr** [jonathanmann/Rummikub#1]
For sake of example assume one of the 4's is the same color as the [1, 2, 3] run.

```python
public_space = [[1, 2, 3], [4, 4, 4]]
my_hand = [5, 6]

play(somebot) 
public_space = [[1,2,3,4,5,6]]
my_new_hand = [4, 4]
```

I took tiles out of the public space and into my own hand - as I understand it the public space can only change by addition of tiles.

**Comment by jonathanmann** [comment]
Actually, this is a valid move. The public space can be changed in any way that doesn't violate the final two rules of the simplified version as specified in the README:

- A bot may rearrange tiles in the public space or take tiles out of the public space into their hand as long as all collections in the public space are valid at the end of the bot's turn.
- If a bot does not end up with few tiles in its hand than when it began, it must draw a tile

Although this is a valid configuration, since there are the same number of tiles on the board as when the bot started, the rules engine would force the bot to draw a tile. The simplified rules were designed to give the bots strategic flexibility.

**Comment by nchaudhr** [comment]
Ah ok, thanks for clarifying.
